# Generated by Django 5.2 on 2025-05-30 08:48

import taskflow.myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, help_text='Upload a profile photo (max 2MB, formats: JPG, PNG, WebP)', null=True, upload_to='user_photos/', validators=[taskflow.myapp.models.validate_image_file_extension, taskflow.myapp.models.validate_file_size]),
        ),
    ]
